apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v010-deployment
  labels:
    app: myapp-v010
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-v010
  template:
    metadata:
      labels:
        app: myapp-v010
    spec:
      containers:
      - name: myapp-v010
        image: ghcr.io/danielodriscoll/devops-portfolio:v0.1.0   
        ports:
        - containerPort: 80
