
apiVersion: v1
kind: Secret 
metadata:
  name: fastapi-secret
  namespace: default 
type: Opaque

data:
  PLACEHOLDER: ""     #empty for now, real example would be doen securely with valult or AWS secrets
